version: "3"
services: 
  app.test:
    build:
      context: .
      dockerfile: Dockerfile
    image: appambienteeducativoback-1.0
    ports:
      - "${APP_PORT:-8000}:8000"
      - "${APP_PORTHTTPS:-443}:443"
    volumes:
     - ".:/code"