insert into cat_tipos_membresias (nombre) values ('trimf	'	);
insert into cat_tipos_membresias (nombre) values ('trapmf  ' );
insert into cat_tipos_membresias (nombre) values ('gbellmf ' );
insert into cat_tipos_membresias (nombre) values ('gaussmf ' );
insert into cat_tipos_membresias (nombre) values ('gauss2mf' );
insert into cat_tipos_membresias (nombre) values ('sigmf   ' );
insert into cat_tipos_membresias (nombre) values ('dsigmf  ' );
insert into cat_tipos_membresias (nombre) values ('psigmf  ' );
insert into cat_tipos_membresias (nombre) values ('pimf    ' );
insert into cat_tipos_membresias (nombre) values ('smf     ' );
insert into cat_tipos_membresias (nombre) values ('zmf     ' );
