insert into cat_preguntas (id_materia,nivel,pregunta) values (1,1,'¿Qué es la física?'																	        );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,1,'¿Cuál es la fórmula para calcular la velocidad?'                                             );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,1,'¿Qué es la aceleración?'                                                                     );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,1,'¿Qué unidad se usa para medir la longitud?'                                                  );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,1,'¿Cuál es la ley de la inercia de Newton?'                                                    );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,1,'¿Qué es un movimiento rectilíneo?'                                                           );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,1,'¿Cómo se mide la temperatura en grados Celsius?'                                             );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,1,'¿Qué es la masa atómica?'                                                                    );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,1,'¿Qué es la inercia?'                                                                         );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,1,'¿Cuál es la tercera ley de Newton?'                                                          );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,2,'¿Qué es la energía cinética?'                                                                );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,2,'¿Cuál es la diferencia entre velocidad y velocidad media?'                                   );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,2,'¿Qué es la fricción?'                                                                        );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,2,'¿Qué es la masa?'                                                                            );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,2,'¿Qué es la masa?'                                                                            );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,2,'¿Qué es la fuerza centrífuga?'                                                               );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,2,'¿Qué es la energía potencial gravitatoria?'                                                  );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,2,'¿Cuál es la diferencia entre velocidad y velocidad instantánea?'                             );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,2,'¿Qué es un vector?'                                                                          );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,2,'¿Cuál es la ecuación de la ley de Hooke?'                                                    );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,3,'¿Qué es la fuerza gravitatoria?'                                                             );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,3,'¿Cómo se calcula el trabajo mecánico?'                                                       );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,3,'¿Qué es el principio de la palanca?'                                                         );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,3,'¿Cuál es la ecuación de la segunda ley de Newton?'                                           );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,3,'¿Qué es la teoría de la relatividad de Einstein?'                                            );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,3,'¿Cuál es la ley de Pascal?'                                                                  );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,3,'¿Qué es el momento de inercia?'                                                              );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,3,'¿Cómo se calcula la aceleración debida a la gravedad en la Tierra?'                          );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,3,'¿Qué es un péndulo simple?'                                                                  );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,3,'¿Cuál es el principio de conservación de la cantidad de movimiento?'                         );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,4,'¿Qué es la óptica geométrica?'                                                               );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,4,'¿Cuál es la fórmula de la ley de la gravitación universal de Newton?'                        );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,4,'¿Qué es la energía potencial?'                                                               );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,4,'¿Cuál es la ecuación de la ley de Ohm?'                                                      );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,4,'¿Qué es un campo eléctrico?'                                                                 );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,4,'¿Qué es la presión atmosférica?'                                                             );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,4,'¿Cuál es la diferencia entre conductores y aislantes eléctricos?'                            );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,4,'¿Qué es un transformador eléctrico?'                                                         );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,4,'¿Qué es un espejo cóncavo?'                                                                  );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,4,'¿Cuál es la ecuación de la ley de Ampere?'                                                   );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,5,'¿Qué es un circuito en serie?'                                                               );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,5,'¿Cuál es la ley de Faraday de la inducción electromagnética?'                                );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,5,'¿Qué es un semiconductor?'                                                                   );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,5,'¿Cuál es la ecuación de la ley de Coulomb?'                                                  );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,5,'¿Qué es un fotón?'                                                                           );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,5,'¿Qué es un circuito en paralelo?'                                                            );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,5,'¿Cuál es la ley de Lenz?'                                                                    );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,5,'¿Qué es el efecto fotoeléctrico?'                                                            );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,5,'¿Cuál es la diferencia entre energía cinética y energía potencial?'                          );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,5,'¿Qué es la constante de Planck?'                                                             );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,6,'¿Cuál es el principio de la conservación del momento angular?'                               );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,6,'¿Qué es la teoría cuántica?'                                                                 );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,6,'¿Cómo se calcula la frecuencia de un oscilador armónico simple?'                             );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,6,'¿Cuál es el principio de la tercera ley de Kepler?'                                          );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,6,'¿Qué es la teoría de cuerdas?'                                                               );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,6,'¿Qué es la radiactividad?'                                                                   );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,6,'¿Cómo se calcula la frecuencia de resonancia de un tubo de órgano?'                          );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,6,'¿Qué es la energía oscura?'                                                                  );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,6,'¿Cuál es el principio de la relatividad especial?'                                           );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,6,'¿Qué es un quark?'                                                                           );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,7,'¿Qué es un agujero negro?'                                                                   );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,7,'¿Cuál es el principio de incertidumbre de Heisenberg?'                                       );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,7,'¿Qué es la teoría de la relatividad general?'                                                );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,7,'¿Cuál es el concepto de entropía en la termodinámica?'                                       );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,7,'¿Cómo se define la carga eléctrica?'                                                         );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,7,'¿Qué es la teoría de cuerdas?'                                                               );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,7,'¿Cómo funciona un acelerador de partículas?'                                                 );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,7,'¿Cuál es la teoría de la gran unificación?'                                                  );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,7,'¿Qué es la paradoja de la información en los agujeros negros?'                               );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,7,'¿Qué es la teoría de las cuerdas vibrantes?'                                                 );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,8,'¿Cuál es la estructura del átomo?'                                                           );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,8,'¿Qué es la radiación electromagnética?'                                                      );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,8,'¿Cuál es la ecuación de Schrödinger?'                                                        );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,8,'¿Qué es la teoría de la supercuerda?'                                                        );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,8,'¿Cuál es la teoría del big bang?'                                                            );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,8,'¿Cuál es la teoría del todo?'                                                                );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,8,'¿Qué es el bosón de Higgs?'                                                                  );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,8,'¿Cómo se relaciona la relatividad general con la teoría cuántica?'                           );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,8,'¿Qué es la teoría del multiverso?'                                                           );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,8,'¿Qué es la supersimetría?'                                                                   );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,9,'¿Qué es la materia oscura?'                                                                  );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,9,'¿Cómo funciona un acelerador de partículas?'                                                 );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,9,'¿Qué es la teoría de las cuerdas?'                                                           );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,9,'¿Cuál es la hipótesis del multiverso?'                                                       );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,9,'¿Qué es la teoría de la gran unificación?'                                                   );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,9,'¿Qué es la teoría de la inflación en cosmología?'                                            );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,9,'¿Qué es la teoría del multiverso cuántico?'                                                  );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,9,'¿Cuál es la paradoja de los gemelos en la relatividad?'                                      );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,9,'Explique el concepto de la teoría M en la física de partículas.'                             );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,9,'¿Qué son las partículas elementales?'                                                        );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,10,'¿Cuál es la fórmula para calcular la velocidad?'                                            );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,10,'Explique la teoría de la relatividad de Einstein en detalle.'                               );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,10,'Describa el experimento de la doble rendija y su implicación en la mecánica cuántica.'      );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,10,'¿Qué es la paradoja del gato de Schrödinger?'                                               );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,10,'Explique el concepto de la teoría M en la física de partículas.'                            );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,10,'¿Cuáles son los desafíos actuales en la física teórica?'                                    );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,10,'Explique la teoría de cuerdas en detalle.'                                                  );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,10,'Describa el concepto de gravedad cuántica.'                                                 );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,10,'¿Qué es la paradoja del horizonte en la física de agujeros negros?'                         );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,10,'Explique el principio holográfico.'                                                         );
insert into cat_preguntas (id_materia,nivel,pregunta) values (1,10,'¿Cuáles son las implicaciones de la teoría de cuerdas para la física moderna?'				);
